--[[ Entity Class
An entity describes any generated game object
By default, it has:
(1) an ID (generated by the Entity Manager which keeps a count of all the generated IDs)
(2) a given name which can be nil

Components can be added to an entity
--]]

local Entity = {}
Entity.__index = Entity

-- Create new entity
function Entity:new(id, name)
        local entity = {}
        setmetatable(entity, self)

        self.id = id
        self.name = name
        return entity
end

return Entity