--[[ Entity Class
An entity describes any generated game object
By default, it has an ID (generated by the Entity Manager) and a given name
--]]

local Entity = {}
Entity.__index = Entity

-- Create new player at starting x and y coordinates
function Entity:new(id, name)
        local entity = {}
        setmetatable(entity, self)

        self.id = id
        self.name = name
        return entity
end

return Entity